### ISSUE TITLE
Cant install using pip

### ISSUE THREAD

**Issue by dionealfarisi** [NixOS/patchelf#567]
**Describe the bug**

I am try install patchelf in Termux but error

**Steps To Reproduce**

pip install patchelf

**ERROR**
###~ $ pip install patchelf
Collecting patchelf
  Using cached patchelf-0.17.2.1.tar.gz (167 kB)    Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: patchelf
  Building wheel for patchelf (pyproject.toml) ... error
  error: subprocess-exited-with-error             
  × Building wheel for patchelf (pyproject.toml) did not run successfully.                            │ exit code: 1
  ╰─> [86 lines of output]                        

      --------------------------------------------------------------------------------                    -- Trying 'Ninja' generator
      --------------------------------                  ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is Clang 19.1.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is Clang 19.1.1
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (4.5s)
      -- Generating done (0.1s)
      -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/_skbuild/linux-armv7l-3.12/cmake-build
        Command:
          /data/data/com.termux/files/usr/bin/cmake /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc -G Ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/_skbuild/linux-armv7l-3.12/cmake-install -DPYTHON_VERSION_STRING:STRING=3.12.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/data/data/com.termux/files/usr/tmp/pip-build-env-6mio14po/overlay/lib/python3.12/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3.12 -DPYTHON_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.12 -DPYTHON_LIBRARY:PATH=/data/data/com.termux/files/usr/lib/libpython3.12.so -DPython_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3.12 -DPython_ROOT_DIR:PATH=/data/data/com.termux/files/usr -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.12 -DPython3_EXECUTABLE:PATH=/data/data/com.termux/files/usr/bin/python3.12 -DPython3_ROOT_DIR:PATH=/data/data/com.termux/files/usr -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.12 -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- The C compiler identification is Clang 19.1.1
      -- The CXX compiler identification is Clang 19.1.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (4.2s)
      -- Generating done (0.1s)
      -- Build files have been written to: /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/_skbuild/linux-armv7l-3.12/cmake-build
      [1/10] Creating directories for 'build_patchelf'
      [2/10] No download step for 'build_patchelf'
      [3/10] No update step for 'build_patchelf'
      [4/10] Performing patch step for 'build_patchelf'
      FAILED: build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/_skbuild/linux-armv7l-3.12/cmake-build/build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch
      cd /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/src/patchelf-upstream && ./bootstrap.sh && /data/data/com.termux/files/usr/bin/cmake -E touch /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/_skbuild/linux-armv7l-3.12/cmake-build/build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch
      ./bootstrap.sh: 2: autoreconf: not found
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-6mio14po/overlay/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 668, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-6mio14po/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 696, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-6mio14po/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 741, in make_impl
          raise SKBuildError(msg)

      An error occurred while building with CMake.
        Command:
          /data/data/com.termux/files/usr/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc
        Working directory:
          /data/data/com.termux/files/usr/tmp/pip-install-5x1qu5vf/patchelf_81783c422c5b44d2ad9c5957e64e61dc/_skbuild/linux-armv7l-3.12/cmake-build
      Please check the install target is valid and see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for patchelf
Failed to build patchelf
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (patchelf)
~ $

**Comment by Mic92** [comment]
Hello. We are not maintaining the patchelf pypi package. Please report the issue with the owner of this package.

**Comment by Mic92** [comment]
However to hint you to a solution. It looks like you are missing autoreconf.

**Comment by dionealfarisi** [comment]
> Hello. We are not maintaining the patchelf pypi package. Please report the issue with the owner of this package.

It's fixed , It was my fault
